# Generated by Django 5.1.5 on 2025-02-07 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_remove_customuser_role_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_doc', models.FileField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('plus2_doc', models.FileField(blank=True, null=True, upload_to='documents/plus2/')),
                ('sslc_doc', models.FileField(blank=True, null=True, upload_to='documents/sslc/')),
                ('income_cert_doc', models.FileField(blank=True, null=True, upload_to='documents/income_certificate/')),
                ('nc_cert_doc', models.FileField(blank=True, null=True, upload_to='documents/ncc_certificate/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
    ]
