# Generated by Django 5.1.5 on 2025-02-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_studentdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDocument',
        ),
    ]
