# Generated by Django 4.2.11 on 2025-01-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('scholarship_id', models.AutoField(primary_key=True, serialize=False)),
                ('scholarship_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
