# Generated by Django 5.1.5 on 2025-01-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_scholarship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
