# Generated by Django 5.1.5 on 2025-02-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_delete_studentdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=255, unique=True)),
                ('max_mark', models.PositiveIntegerField()),
            ],
        ),
    ]
