# Generated by Django 5.1.5 on 2025-02-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_marks', models.FloatField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.board')),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stud', 'board'), name='unique_student_board')],
            },
        ),
    ]
