# Generated by Django 5.1.5 on 2025-02-10 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_qualifiedmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='qualifiedmark',
            name='unique_student_board',
        ),
        migrations.RenameField(
            model_name='qualifiedmark',
            old_name='stud',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='Null', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.student'),
        ),
        migrations.AddConstraint(
            model_name='qualifiedmark',
            constraint=models.UniqueConstraint(fields=('student', 'board'), name='unique_student_board'),
        ),
        migrations.AddField(
            model_name='student',
            name='pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.pathway'),
        ),
    ]
