# Generated by Django 5.1.5 on 2025-01-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('Malayalam', 'Malayalam'), ('Hindi', 'Hindi')], default='Malayalam', max_length=10),
        ),
    ]
