# Generated by Django 5.1.5 on 2025-02-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_qualifiedmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiedmark',
            name='stud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student'),
        ),
    ]
