# Generated by Django 5.1.5 on 2025-02-03 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_student_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='stud_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('tc_no', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_application', models.DateField()),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('reason_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.reason')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
    ]
