 Generated by Django 5.1.5 on 2025-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_pathway_remove_student_id_remove_user_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qualifiedmark',
            name='unique_student_board',
        ),
        migrations.RenameField(
            model_name='qualifiedmark',
            old_name='stud',
            new_name='student',
        ),
        migrations.AddConstraint(
            model_name='qualifiedmark',
            constraint=models.UniqueConstraint(fields=('student', 'board'), name='unique_student_board'),
        ),
    ]
