# Generated by Django 5.1.5 on 2025-02-11 05:21

import admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_pathway_student_pathway'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='student',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/income/'),
        ),
        migrations.AddField(
            model_name='student',
            name='ncc_nss_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/ncc_nss/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/photos/', validators=[admission.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='student',
            name='plus_two_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/plus_two/'),
        ),
        migrations.AddField(
            model_name='student',
            name='sslc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/sslc/'),
        ),
    ]
