# Generated by Django 5.1.5 on 2025-02-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_pathway_remove_qualifiedmark_unique_student_board_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfercertificate',
            old_name='stud',
            new_name='student',
        ),
    ]
