# Generated by Django 5.1.5 on 2025-02-10 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_student_pathway'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.user'),
        ),
    ]
