# Generated by Django 5.1.5 on 2025-02-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_reason_remove_student_id_student_stud_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfercertificate',
            name='reason_id',
        ),
        migrations.RemoveField(
            model_name='transfercertificate',
            name='stud_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_id',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
        migrations.DeleteModel(
            name='TransferCertificate',
        ),
    ]
