# Generated by Django 5.1.5 on 2025-02-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_student_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
