# Generated by Django 5.1.5 on 2025-02-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
