# Generated by Django 5.1.5 on 2025-02-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_reason_transfercertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_reg_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stud_roll_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
