# Generated by Django 5.1.5 on 2025-02-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_remove_user_user_id_user_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='student',
        ),
    ]
