# Generated by Django 5.1.5 on 2025-02-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='user_id',
        ),
    ]
