# Generated by Django 5.1.5 on 2025-02-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_programlevel_student_program_program_program_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlevel',
            name='program_level',
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.department'),
        ),
        migrations.AddField(
            model_name='programlevel',
            name='level_name',
            field=models.CharField(default='UG', max_length=100),
        ),
    ]
