# Generated by Django 5.1.5 on 2025-02-04 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_remove_programlevel_program_level_program_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Null', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='caste',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.category'),
            preserve_default=False,
        ),
    ]
