# Generated by Django 5.1.5 on 2025-02-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0016_studentscholarship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentScholarship',
        ),
    ]
