# Generated by Django 5.1.5 on 2025-02-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_remove_qualifiedmark_unique_student_board_and_more'),
        ('admission', '0008_rename_stud_transfercertificate_student'),
        ('admission', '0008_student_pathway'),
        ('admission', '0016_remove_student_id_remove_student_user_id_and_more'),
    ]

    operations = [
    ]
