# Generated by Django 5.1.5 on 2025-02-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_studentscholarship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='scholarship_name',
            new_name='name',
        ),
    ]
