# Generated by Django 5.1.5 on 2025-02-06 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.type'),
        ),
    ]
