# Generated by Django 5.1.5 on 2025-02-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_scholarship_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='type',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.CharField(choices=[('central', 'Central'), ('state', 'State')], default='Central', max_length=10),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
