# Generated by Django 5.1.5 on 2025-02-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0023_remove_scholarship_type_scholarship_scholarship_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.CharField(choices=[('central', 'Central'), ('state', 'State')], default='Null', max_length=10),
        ),
    ]
