# Generated by Django 5.1.5 on 2025-02-06 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_alter_scholarship_scholarship_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='scholarship_type',
        ),
    ]
