# Generated by Django 5.1.5 on 2025-02-06 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_scholarshiptype_scholarship_scholarship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.scholarshiptype'),
        ),
    ]
