# Generated by Django 5.1.5 on 2025-02-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0028_customuser'),
    ]

    operations = [
    ]
